export enum LocalStorageKey {
  LAST_GENERATION_SETTINGS = 'RP_LAST_GENERATION_SETTINGS',
  LANGUAGE = 'RP_LANGUAGE',
  OFFLINE_EVENTS = 'RP_OFFLINE_EVENTS',
  PALETTE = 'RP_PALETTE',
  PALETTE_TMP = 'RP_PALETTE_TMP',
  THEME = 'RP_THEME',
  USER_ID = 'RP_USER_ID',
}
