export enum TrackingEventCategory {
  EXPORT_PALETTE = 'EXPORT_PALETTE',
  GENERATE_PALETTE = 'GENERATE_PALETTE',
  OFFLINE_EVENTS = 'OFFLINE_EVENTS',
  PWA = 'PWA',
  SAVE_PALETTE = 'SAVE_PALETTE',
  TEST = 'TEST_CATEGORY',
}

export enum TrackingEventAction {
  EXPORT_PALETTE_COPY = 'EXPORT_PALETTE_COPY',
  EXPORT_PALETTE_FILE = 'EXPORT_PALETTE_FILE',
  EXPORT_PALETTE_REQUEST_FORMAT = 'EXPORT_PALETTE_REQUEST_FORMAT',
  GENERATE_PALETTE = 'GENERATE_PALETTE',
  OFFLINE_EVENTS = 'OFFLINE_EVENTS',
  PWA_INSTALL = 'PWA_INSTALL',
  PWA_UPDATE_COMPLETED = 'PWA_UPDATE_COMPLETED',
  PWA_UPDATE_FAILED = 'PWA_UPDATE_FAILED',
  SAVE_PALETTE_LOCAL_STORAGE = 'SAVE_PALETTE_LOCAL_STORAGE',
  TEST = 'TEST_ACTION',
}

export enum TrackingEventName {
  EXPORT_PALETTE_CSS = 'EXPORT_PALETTE_CSS',
  EXPORT_PALETTE_LESS = 'EXPORT_PALETTE_LESS',
  EXPORT_PALETTE_SCSS = 'EXPORT_PALETTE_SCSS',
  EXPORT_PALETTE_TAILWIND = 'EXPORT_PALETTE_TAILWIND',
  EXPORT_PALETTE_UNKNOWN = 'EXPORT_PALETTE_UNKNOWN',
  GENERATE_PALETTE_ANALOGOUS = 'GENERATE_PALETTE_ANALOGOUS',
  GENERATE_PALETTE_COMPLEMENTARY = 'GENERATE_PALETTE_COMPLEMENTARY',
  GENERATE_PALETTE_MONOCHROME = 'GENERATE_PALETTE_MONOCHROME',
  GENERATE_PALETTE_RAINBOW = 'GENERATE_PALETTE_RAINBOW',
  GENERATE_PALETTE_SPLIT_COMPLEMENTARY = 'GENERATE_PALETTE_SPLIT_COMPLEMENTARY',
  GENERATE_PALETTE_SQUARE = 'GENERATE_PALETTE_SQUARE',
  GENERATE_PALETTE_SURPRISE = 'GENERATE_PALETTE_SURPRISE',
  GENERATE_PALETTE_TETRADIC = 'GENERATE_PALETTE_TETRADIC',
  GENERATE_PALETTE_TRIADIC = 'GENERATE_PALETTE_TRIADIC',
  GENERATE_PALETTE_UNKNOWN = 'GENERATE_PALETTE_UNKNOWN',
  TEST = 'TEST_NAME',
}
