name: Feature Request
description: Request a new feature for Rainbow Palette
title: '[Feature]: '
labels: ['status/new', 'type/feature']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
        We'll do our best to add your requested feature to Rainbow Palette.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: feature-name
    attributes:
      label: Feature Name
      description: What is the name of the feature you'd like to request?
      placeholder: ex. MyFeature
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to request in detail
      placeholder: Tell us about your feature!
    validations:
      required: true
