import { Color } from '../model/color.model';
import { Palette } from '../model/palette.model';
import { Shade } from '../model/shade.model';
import { Formatter } from '../interfaces/formatter.interface';

export class CssFormatter implements Formatter {
  filename = 'colors.css';
  mimeType = 'text/css';

  formatFile(palette: Palette): string {
    const content = this.formatPalette(palette).replace(/\n/g, '\n\t');

    return `:root {\n\t${content}\n}`;
  }

  formatPalette(palette: Palette): string {
    const content = palette.colors
      .map((color) => this.formatColor(color))
      .join('\n\n');

    return `/* Color palette generated by ${window.location.origin} */\n\n${content}`;
  }

  formatColor(color: Color): string {
    const name = color.name.replace(/\s+/g, '-').toLowerCase();
    const shades = color.shades
      .map((shade) => this.formatShade(shade, name))
      .join('\n');

    return shades;
  }

  formatShade(shade: Shade, name: string): string {
    return `--${name}-${shade.index}:${shade.index < 100 ? ' ' : ''} ${
      shade.hex
    };`;
  }
}
