name: 🚀 Deploy website on push

on:
  push:
    branches:
    - deploy
  pull_request:
    branches:
    - deploy

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.1.0
      
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build

    - name: 📂 Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        host: ${{ secrets.ftp_host }}
        user: ${{ secrets.ftp_user }}
        key: ${{ secrets.ssh_private_key }}
        local: './dist/'
        remote: '~/color-generator'
        scp_options: -v
