import { Exporter } from '../interfaces/exporter.interface'
import { Color } from '../models/color.model'
import { Palette } from '../models/palette.model'
import { Shade } from '../models/shade.model'

export class LessExporter implements Exporter {
  /**
   * Export a palette for usage in a separate colors.less file.
   * @param palette Palette to export
   */
  exportFile(palette: Palette) {
    return `// Import the variables into your LESS files with\n\t@import "colors.less";\n\n${this.exportContent(
      palette
    )}`
  }

  /**
   * Export a palette for usage in LESS as variables.
   * @param palette Palette to export
   */
  exportContent(palette: Palette) {
    return `// Color palette generated by ${
      window.location.origin
    }\n\n${palette.colors.map((c) => this.exportColorToLESS(c)).join('\n\n')}`
  }

  /**
   * Export a color for usage in LESS as variables.
   * @param color Color to export
   */
  private exportColorToLESS(color: Color) {
    const name = color.name.replace(/\s+/g, '-').toLowerCase()
    return color.shades.map((s) => this.exportShadeToLESS(s, name)).join('\n')
  }

  /**
   * Export a shade for usage in LESS as variable.
   * @param shade Shade to export
   * @param name Name of the color
   */
  private exportShadeToLESS(shade: Shade, name: string) {
    return `@${name}-${shade.index}:${shade.index < 100 ? ' ' : ''} ${
      shade.hex
    };`
  }
}
